#!/bin/bash
# =============================================================================
# SCRIPT 2 OF 2 — HARDENING
#
# Run this ONLY after you have verified that:
#   ssh -p 22 -i ~/.ssh/trading_vps deploy@<your-droplet-ip>
# works correctly from your Mac.
#
# What it does:
#   - Changes SSH port from 22 to 2222
#   - Disables password authentication (key-only)
#   - Disables root login
#   - Enables ufw firewall (port 2222 only)
#   - Configures fail2ban
#   - Enables automatic security updates
#   - Creates systemd services for bot and strategy
#   - Creates emergency kill script
#
# IMPORTANT: Do NOT close your current SSH session until you have
# confirmed login works on port 2222 in a second terminal window.
# =============================================================================

set -euo pipefail
IFS=$'\n\t'

# =============================================================================
# CONFIGURATION
# =============================================================================

NEW_USER="deploy"
SSH_PORT="2222"

# =============================================================================
# HELPERS
# =============================================================================

log()  { echo -e "\n\033[1;32m>>> $1\033[0m"; }
warn() { echo -e "\033[1;33mWARN: $1\033[0m"; }

if [[ $EUID -ne 0 ]]; then
    echo "Run as root" >&2
    exit 1
fi

# Verify deploy user exists before hardening
if ! id "$NEW_USER" &>/dev/null; then
    echo "ERROR: User $NEW_USER does not exist." >&2
    echo "Run setup_base.sh first." >&2
    exit 1
fi

# Verify deploy user has an SSH key installed
if [[ ! -s /home/$NEW_USER/.ssh/authorized_keys ]]; then
    echo "ERROR: No SSH key found for $NEW_USER." >&2
    echo "Hardening SSH now would lock you out." >&2
    echo "Fix SSH key first, then re-run this script." >&2
    exit 1
fi

log "Pre-flight checks passed — deploy user exists and has SSH key"
echo ""
warn "REMINDER: Keep this session open until you verify SSH works on port $SSH_PORT"
echo ""

# =============================================================================
# 1. SSH HARDENING
# =============================================================================

log "Hardening SSH configuration"

SSHD_CONFIG="/etc/ssh/sshd_config"
cp $SSHD_CONFIG ${SSHD_CONFIG}.bak

cat > $SSHD_CONFIG << EOF
# Hardened SSH config — generated by setup_harden.sh

Port $SSH_PORT
Protocol 2

# Key-only auth, no root login
PermitRootLogin no
PasswordAuthentication no
PubkeyAuthentication yes
AuthorizedKeysFile .ssh/authorized_keys
ChallengeResponseAuthentication no
UsePAM no

# Reduce attack surface
X11Forwarding no
AllowAgentForwarding no
AllowTcpForwarding no
PrintMotd no
AcceptEnv LANG LC_*

# Timeouts
LoginGraceTime 20
ClientAliveInterval 300
ClientAliveCountMax 2
MaxAuthTries 3
MaxSessions 3

# Whitelist only deploy user
AllowUsers $NEW_USER
EOF

systemctl restart sshd
log "SSH restarted on port $SSH_PORT"

# =============================================================================
# 2. FIREWALL
# =============================================================================

log "Configuring firewall"

ufw default deny incoming
ufw default allow outgoing
ufw allow ${SSH_PORT}/tcp comment "SSH"
ufw --force enable

ufw status verbose

# =============================================================================
# 3. FAIL2BAN
# =============================================================================

log "Configuring fail2ban"

cat > /etc/fail2ban/jail.local << EOF
[DEFAULT]
bantime  = 1h
findtime = 10m
maxretry = 3
backend  = systemd

[sshd]
enabled = true
port    = $SSH_PORT
EOF

systemctl enable fail2ban
systemctl restart fail2ban

# =============================================================================
# 4. AUTOMATIC SECURITY UPDATES
# =============================================================================

log "Enabling automatic security updates"

cat > /etc/apt/apt.conf.d/50unattended-upgrades << 'EOF'
Unattended-Upgrade::Allowed-Origins {
    "${distro_id}:${distro_codename}-security";
};
Unattended-Upgrade::AutoFixInterruptedDpkg "true";
Unattended-Upgrade::MinimalSteps "true";
Unattended-Upgrade::Remove-Unused-Dependencies "true";
Unattended-Upgrade::Automatic-Reboot "false";
EOF

cat > /etc/apt/apt.conf.d/20auto-upgrades << 'EOF'
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Unattended-Upgrade "1";
EOF

# =============================================================================
# 5. LOG ROTATION
# =============================================================================

log "Configuring log rotation"

cat > /etc/logrotate.d/trading << EOF
/home/$NEW_USER/trading/logs/*.log {
    daily
    rotate 30
    compress
    missingok
    notifempty
    create 0640 $NEW_USER $NEW_USER
}
EOF

# =============================================================================
# 6. SYSTEMD SERVICES
# =============================================================================

log "Creating systemd services"

CONDA_PYTHON="/home/$NEW_USER/miniforge3/envs/trading/bin/python"

# Telegram bot service
cat > /etc/systemd/system/trading-bot.service << EOF
[Unit]
Description=Trading System — Telegram Bot
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$NEW_USER
WorkingDirectory=/home/$NEW_USER/trading
ExecStart=$CONDA_PYTHON /home/$NEW_USER/trading/scripts/bot.py
Restart=on-failure
RestartSec=10s
StandardOutput=journal
StandardError=journal
SyslogIdentifier=trading-bot

NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ReadWritePaths=/home/$NEW_USER/trading

[Install]
WantedBy=multi-user.target
EOF

# Strategy service — enable manually once strategy.py is in place
cat > /etc/systemd/system/trading-strategy.service << EOF
[Unit]
Description=Trading System — Strategy Runner
After=network-online.target trading-bot.service
Wants=network-online.target

[Service]
Type=simple
User=$NEW_USER
WorkingDirectory=/home/$NEW_USER/trading
ExecStart=$CONDA_PYTHON /home/$NEW_USER/trading/scripts/strategy.py
Restart=on-failure
RestartSec=30s
StandardOutput=journal
StandardError=journal
SyslogIdentifier=trading-strategy

NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ReadWritePaths=/home/$NEW_USER/trading

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable trading-bot.service
log "Systemd services created — bot enabled, strategy needs strategy.py first"

# =============================================================================
# 7. EMERGENCY KILL SCRIPT
# =============================================================================

log "Writing emergency kill script"

cat > /home/$NEW_USER/trading/kill.sh << 'EOF'
#!/bin/bash
# Emergency kill — use when Telegram is unreachable
echo "Activating emergency kill switch..."

echo "1" > /tmp/KILL_SWITCH
echo "  [1/3] Kill switch file written"

sqlite3 ~/trading/data/state.db \
    "INSERT OR REPLACE INTO state (key, value) VALUES ('kill_switch', '1');"
echo "  [2/3] Kill switch set in database"

systemctl stop trading-strategy.service 2>/dev/null && \
    echo "  [3/3] Strategy service stopped" || \
    echo "  [3/3] Strategy service was not running"

echo ""
echo "Done. Run 'systemctl start trading-strategy' to restart."
EOF

chmod +x /home/$NEW_USER/trading/kill.sh
chown $NEW_USER:$NEW_USER /home/$NEW_USER/trading/kill.sh

# =============================================================================
# DONE
# =============================================================================

log "Hardening complete"

echo ""
echo "============================================================"
echo "  HARDENING COMPLETE"
echo "============================================================"
echo ""
echo "  !! DO NOT CLOSE THIS SESSION YET !!"
echo ""
echo "  Open a NEW terminal and verify login works:"
echo "  ssh -p 2222 -i ~/.ssh/trading_vps $NEW_USER@$(hostname -I | awk '{print $1}')"
echo ""
echo "  Or if you have the ssh config entry:"
echo "  ssh trading-vps"
echo ""
echo "  Only close this session after confirming the above works."
echo ""
echo "  NEXT STEPS (once logged in as deploy):"
echo "  1. cp ~/trading/config/secrets.env.template ~/trading/config/secrets.env"
echo "  2. nano ~/trading/config/secrets.env   (fill in tokens)"
echo "  3. conda run -n trading python ~/trading/scripts/init_db.py"
echo "  4. sudo systemctl start trading-bot"
echo "  5. Update ~/.ssh/config on your Mac: change Port to 2222"
echo "  6. Take a DO snapshot as your clean baseline"
echo "============================================================"
